name: Sync Fork

on:
  schedule:
    - cron: '10 10 * * *'      # every day
  workflow_dispatch:          # on button click

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync upstream 

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: Pull upstream 
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
      with:
        upstream_repository: equinor/webviz-core-components
        upstream_branch: master

        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gha-sync-branch
        
        # Set test_mode true to run tests instead of the true action!!
        test_mode: true
